### ISSUE TITLE
Link to the example is broken in documentation

### ISSUE THREAD

**Issue by IohannRabeson** [kotauskas/interprocess#41] opened 2023-07-11 23:59 UTC
**Describe the bug**
The link to the example "Basic server" is broken in this page https://docs.rs/interprocess/latest/interprocess/local_socket/tokio/struct.LocalSocketListener.html

**Comment by kotauskas** [comment] 2023-07-12 10:38
Duplicate of #39.

**Closed by kotauskas** 2023-07-12 10:38 UTC
Labels: bug
