### ISSUE TITLE
Docs link to nonexistent examples

### ISSUE THREAD

**Issue by yanqui-uxo** [kotauskas/interprocess#54] opened 2024-02-13 01:17 UTC
For example, at https://docs.rs/interprocess/latest/interprocess/local_socket/struct.LocalSocketListener.html, there is a link to a "basic server" that results in a 404. I note there are examples within the source on Github, but not on docs.rs - there seems to be a desync there.

**Comment by kotauskas** [comment] 2024-02-13 14:32
Duplicate of #39.

**Closed by kotauskas** 2024-02-13 14:32 UTC
