### ISSUE TITLE
All links to examples point to 404

### ISSUE THREAD

**Issue by ThrasherLT** [kotauskas/interprocess#59] opened 2024-04-23 11:10 UTC
**Describe the bug**
Not sure if this is supposed to happen, because the examples haven't been prepared yet, but all the links to the examples produce 404 errors. I see that the examples folder doesn't even exist, but I'm not sure if they had been deleted by accident or have they never existed in the first place

**To Reproduce**
Here's one of the broken links found in LocalSocketListener docs:
https://github.com/kotauskas/interprocess/blob/main/examples/tokio_local_socket/server.rs

**Expected behavior**
Links to examples point to actual examples. Or at least placeholder TODO pages, because now it looks like it's broken.

**Comment by kotauskas** [comment] 2024-04-26 12:15
Duplicate of #39.

**Closed by kotauskas** 2024-04-26 12:15 UTC
Labels: bug
